### ISSUE TITLE
Pull sqlite Into Own Package

### ISSUE THREAD

**Issue by chaseWillden** [njord-rs/njord#140]
Currently sqlite is embedded in [njord](https://github.com/mjovanc/njord/tree/master/njord/src/sqlite) package. 

For separation of concerns, this should be split out into it's own lib to allow for the other dbs to be implemented.

In short, in order to use this package, the user shouldn't be required to have a certain db

**Comment by mjovanc** [comment]
We don't need that though. We can just use CFG flag for the module itself in lib.rs and Cargo feature flags so it doesn't get included when adding njord as a dependency. If I understood you correctly? Currently we have feature flags for sqlite specifically. 

**As I visioned it, the user should be able to do this:**

```toml
njord = { version = "<version>", features = ["sqlite"] }
```

**Or:**

```toml
njord = { version = "<version>", features = ["postgres"] }
```

**If they don't want the default features they can do this:**

```toml
njord = { version = "<version>", features = ["sqlite"], default-features = false }
```

**Comment by chaseWillden** [comment]
Oh sweet, I didn't know about this. Ok scratch that, I'll close this out
