### ISSUE TITLE
Create better tests structure

### ISSUE THREAD

**Issue by mjovanc** [njord-rs/njord#141]
We are starting to get a lot of tests and eventually it is going to be a huge file for `sqlite`. What I propose is that we do something like this instead:

```
tests
    sqlite
        common_test.rs
        insert_test.rs
        update_test.rs
        delete_test.rs        
        select_test.rs
    postgres
        ...
```

**Comment by Hiccup-za** [comment]
This is definitely the way to go for structuring tests as you build out support for other DBs 🚀

**Comment by mjovanc** [comment]
Thanks! Are you perhaps interested in fixing this? 😎

**Comment by Hiccup-za** [comment]
I'd be more than happy to give it a shot!

**Comment by Hiccup-za** [comment]
Got a branch ready to go

![Screenshot 2024-10-07 at 19 42 28](https://github.com/user-attachments/assets/235cc90a-050d-4def-98fc-73f2f98429c0)

**Comment by mjovanc** [comment]
Hey man, you need to fork the repo first and clone it. Then you push to that forked repo and create PR from your repo to this repo. That's how you do it.
