### ISSUE TITLE
Feature flag doesn't conditionally enable code

### ISSUE THREAD

**Issue by mjovanc** [njord-rs/njord#164]
When trying to use the njord dependency using git repo link as well as feature flag on latest it doesn't activate the specific code. 

**For example adding this:**

```toml
njord = { git = "https://github.com/njord-rs/njord", package = "njord", branch = "master", features = ["sqlite"] }
```

**It should active this code inside `njord/src/lib.rs`:**

```rust
#[cfg(feature = "sqlite")]
pub mod sqlite;
```

**But it doesn't, the Rust analyzer says:** 

> Conditionally disabled code

**Comment by Angr1st** [comment]
I just copied your sqllite example and replaced the njord dependency with your example and it worked fine after also fixing the relative db file path. Maybe it is only a rust analyser issue.

**Comment by mjovanc** [comment]
@Angr1st Thanks for checking this. It might actually be. I'm using IntelliJ with the Rust plugin. We are soon ready for release and if this is not working, that is not good. I will try in VS Code with Rust Analyzer as well to confirm.

**Comment by Angr1st** [comment]
How exactly are you surfacing this error? Im using helix and when I do go to definition of the njord::sqllite it puts me into the sqllite::mod.rs file. If I dont active the sqllite feature I get build errors regarding the missing sqllite module.

**Comment by chaseWillden** [comment]
Hmm, I can't reproduce this issue either, it seems to work fine for me

**Comment by mjovanc** [comment]
Attaching some screenshots just to show. I have done cargo clean, invalidate all caches etc. It seems to be an issue with the Rust plugin and/or IntelliJ. Maybe @bravit can take a look? I have no idea if this is still supported. Closing this for now since you can't reproduce it. 

<img width="921" alt="Screenshot 2024-10-20 at 10 18 29 AM" src="https://github.com/user-attachments/assets/96a4bde7-719a-4ed5-93b3-15cc07df8141">
<img width="1314" alt="Screenshot 2024-10-20 at 10 18 39 AM" src="https://github.com/user-attachments/assets/581ebf1e-a6e6-4f7f-8bb6-cd9b122a0539">
<img width="617" alt="Screenshot 2024-10-20 at 10 18 49 AM" src="https://github.com/user-attachments/assets/d85e0606-ab2a-4c76-aa6c-268d9b1df29f">
