### ISSUE TITLE
MySQL module not listed in Rust docs

### ISSUE THREAD

**Issue by mjovanc** [njord-rs/njord#175]
mysql module is not listed in the docs.

![Screenshot 2024-10-22 at 14 04 37](https://github.com/user-attachments/assets/6bfbc8dc-9604-40f6-a552-c3cf6aae7631)

**Comment by chaseWillden** [comment]
@mjovanc, shouldn't running `cargo doc --all` capture the other packages?

**Comment by mjovanc** [comment]
@chaseWillden We are using `cargo publish` via a plugin in the `release.yml` workflow: https://github.com/katyo/publish-crates/tree/main

The `cargo publish` command should automatically run this.
