### ISSUE TITLE
Add support for subqueries

### ISSUE THREAD

**Issue by mjovanc** [njord-rs/njord#64]
SELECT, INSERT, UPDATE, and DELETE statements.

**Comment by chaseWillden** [comment]
Select Statement (excluding where clause) - https://github.com/mjovanc/njord/pull/135
 - [x] Select
 - [x] Insert
 - [x] Update
 - [x] Delete

**Comment by chaseWillden** [comment]
Insert subquery: https://github.com/mjovanc/njord/pull/146
